# -*- coding: utf-8 -*-
"""netflix content analysis using pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iEgDFyhvKQC5UDpFs8n9WadJupPUJ1He

import libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""load dataset"""

df=pd.read_csv('/content/netflix_dataset.2.csv')

"""explorations"""

df.shape

df.shape
df.info()
df.describe()
df.isnull().sum()

"""data cleaning"""

df['date_added'] = pd.to_datetime(df['date_added'])
df['release_year'] = df['release_year'].astype(int)

"""EDA(exploratory data analysis)

content type distribution
"""

df['type'].value_counts()

"""top countries"""

df['country'].value_counts().head(10)

"""Most Common Genres"""

df['listed_in'].value_counts()

"""Visulaization
Movies vs Tv shows
"""

sns.countplot(x='type', data=df)
plt.show()

"""Top 10 Countries Producing Content"""

df['country'].value_counts().head(10).plot(kind='bar')
plt.show()

"""content released by year"""

df['release_year'].value_counts().sort_index().plot()
plt.show()

"""ratings distribution"""

sns.countplot(y='rating', data=df)
plt.show()